# Capa del proyecto Secure Vision (control de acceso)
BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "control-acceso"
BBFILE_PATTERN_control-acceso = "^${LAYERDIR}/"
BBFILE_PRIORITY_control-acceso = "10"

# core = openembedded-core, openembedded-layer = meta-oe (OpenCV, libgpiod),
# meta-python (python3-gpiod, bindings v2 de libgpiod), raspberrypi = meta-raspberrypi
LAYERDEPENDS_control-acceso = "core openembedded-layer meta-python raspberrypi"

# Todas las capas deben estar en la misma rama. Deje la suya en la lista.
LAYERSERIES_COMPAT_control-acceso = "scarthgap styhead walnascar whinlatter wrynose"
